theme: minima

title: Our Master
author: Selvakumaran Krishnan
email: support@wikimint.com
url: https://www.wikimint.com

timezone: Etc/UTC # GitHub uses UTC. This is to force dev environment to match
future: false # GitHub Pages will publish future posts if this isn't set to false

description: >
  Our Master, a weblog for technical readers about technical information. 

# Minima variables
twitter_username:  wikimint
github_username:   wikimint
linkedin_username: selvakumaran-krishnan
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
rss: rss

show_excerpts: false

# Used by simple links page
social-links:
  LinkedIn:        https://www.linkedin.com/company/wikimintcreations
  StackOverflow:   https://stackoverflow.com/users/3474677
  HackerRank:      https://hackerrank.com/chadwin
  GitHub:          https://github.com/wikimint
  Twitter:         https://twitter.com/wikimint
  Reddit:          https://www.reddit.com/r/wikimintcreations/
  Credly:          https://www.credly.com/users/selvakumaran-krishnan
  Website:         https://www.wikimint.com

# plugin: jekyll-seo-tag
twitter:
  username: wikimint
  card: summary_large_image
social:
  name: Selvakumaran Krishnan
  links:
    - https://twitter.com/selvakumarankri
    - https://linkedin.com/in/selvakumaran-krishnan
    - https://github.com/wikimint

# plugin: jekyll-titles-from-headings
titles_from_headings:
  strip_title: true

collections:
  personal: # collection for personal blog posts
    output: true

header_pages:
  - resume.html
  - archive.html
  - books.md
  - bookmarks.md

plugins:
  - jekyll-feed
  - jekyll-sitemap

google_analytics:
  -  # Old GA Universal Analytics property
  -  # New GA4 property

gravatar_hash: 2136e716a089f4a3794f4007328c7bfb
code_block_max_height: 500px

home_post_limit: 5

# The github repo that is to be used for looking up comments
comments_repo: chadbaldwin/chadbaldwin.github.io

defaults:
  - scope:
      path: ""
    values:
      image: https://s.gravatar.com/avatar/2136e716a089f4a3794f4007328c7bfb?s=800 # Apply default site image
  - scope:
      path: ""
      type: posts
    values:
      tags:
        - Other # Add a default tag to all posts

# Disable highlighting to use highlightJS instead
# highlighter: none # Not supported by GitHub Pages
kramdown:
  syntax_highlighter_opts:
    disable: true
